---
- name: LAMP stack
  hosts: all
  become: true
  vars:
    server_name: pop.com
    document_root: /var/www/html
    PORT: '80'
    CentOS_packages:
      - httpd
      - mariadb-server
      - php
      - php-mysql
    Ubuntu_packages:
      - apache2
      - mysql-server
      - php
      - libapache2-mod-php
      - php-mysql
    copy_files:
      - /home/ansible/files/info.php

  tasks:
    - name: YUM clean
      shell: yum clean all
      when: ansible_os_family == "RedHat"

    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install packages CentOS
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      notify:
        - Start HTTP
        - Start MariaDB
      loop: "{{ CentOS_packages }}"
      when: ansible_os_family == 'RedHat'

    - name: Install packages Ubuntu
      apt:
        name: "{{ item }}"
        state: present
      notify:
        - Start Apache
        - Start MySQL
      loop: "{{ Ubuntu_packages }}"
      when: ansible_os_family == 'Debian'

    - name: Copy files
      copy:
        src: "{{ item }}"
        dest: /var/www/html/info.php
        owner: root
        group: root
        mode: '0644'
      loop: "{{ copy_files }}"

    - name: Copy Apache virtual host configuration
      template:
        src: "/home/ansible/files/virtual_host.j2"
        dest: "/etc/apache2/sites-available/{{ server_name }}.conf"
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == 'Debian'


    - name: Copy httpd virtual host configuration
      template:
        src: "/home/ansible/files/virtual_host.j2"
        dest: "/etc/httpd/conf/{{ server_name }}.conf"
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == 'RedHat'
      notify:
        - restart apache2
        - restart httpd


  handlers:
    - name: Start HTTP
      service:
        name: httpd
        state: started
        enabled: true

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Start MySQL
      service:
        name: mysql
        state: started
        enabled: true

    - name: restart httpd
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: restart apache2
      service:
        name: apache2
        state: restarted
        enabled: true
